/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.mingchuno.aoc

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.booleans.shouldBeTrue

class LibraryTest : FunSpec({ test("some test") { Library().someLibraryMethod().shouldBeTrue() } })
